fan_set_buzzer:
  name: Set buzzer
  description: Turn the buzzer on or off.
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    enabled:
      name: Enabled
      description: True to turn the buzzer on, false to turn it off.
      example: true
      selector:
        boolean:

fan_set_child_lock:
  name: Set child lock
  description: Turn the child lock on or off.
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    enabled:
      name: Enabled
      description: True to turn the child lock on, false to turn it off.
      example: true
      selector:
        boolean:

fan_set_natural_mode:
  name: Set natural mode
  description: Turn the natural mode on or off.
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    enabled:
      name: Enabled
      description: True to turn natural mode on, false to turn it off.
      example: true
      selector:
        boolean:

fan_set_vertical_oscillation:
  name: Set vertical oscillation
  description: Turn the vertical oscillation on or off. (P70 and P76 only)
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    enabled:
      name: Enabled
      description: True to turn vertical oscillation on, false to turn it off.
      example: true
      selector:
        boolean:

fan_set_anion:
  name: Set anion
  description: Turn the anion (ionizer) on or off. (ZA5 only)
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    enabled:
      name: Enabled
      description: True to turn anion on, false to turn it off.
      example: true
      selector:
        boolean:

fan_set_led_brightness:
  name: Set LED brightness
  description: Set the LED brightness.
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    brightness:
      name: Brightness
      description: Brightness (0 = Bright, 1 = Dim, 2 = Off)
      example: 1

fan_set_raw_led_brightness:
  name: Set raw LED brightness
  description: Set the raw LED brightness value (0-100). (ZA5 only)
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    brightness:
      name: Brightness
      description: Raw brightness value (0 = off, 1-100 = on).
      example: 50

fan_set_oscillation_angle:
  name: Set oscillation angle
  description: Set the oscillation angle.
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    angle:
      name: Angle
      description: Supported values are 30, 60, 90, 120, 140 or 150 degrees.
      example: 30

fan_set_delay_off:
  name: Set delay off
  description: Set the scheduled turn off time.
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    delay_off_countdown:
      name: Delay off countdown
      description: Time in minutes. Valid values are 0, 60, 120, 180, 240, 300, 240, 300, 360, 420, 480 minutes.
      example: 60

fan_turn:
  name: Turn
  description: Turn to the given direction. (P76 only)
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    direction:
      name: Direction
      description: Supported values are left, right, up and down.
      example: left

fan_set_vertical_oscillation_angle:
  name: Set vertical oscillation angle
  description: Set the vertical oscillation angle. (P70 and P76 only)
  fields:
    entity_id:
      name: Entity ID
      description: Name of the Xiaomi Mi Smart Fan entity.
      selector:
        entity:
          integration: xiaomi_miio_fan
          domain: fan
    vertical_angle:
      name: Vertical angle
      description: Supported values are 30, 60, 90 or 100 degrees.
      example: 30
